force-app/main/default/objects/Attendees__c/fields/Address__c.field-meta.xml
<CustomField>
    <fullName>Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Address</label>
    <referenceTo>Location_Address_Book__c</referenceTo>
    <relationshipLabel>Attendeess</relationshipLabel>
    <relationshipName>Attendeess</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Attendee__c/fields/Events__c.field-meta.xml
<CustomField>
    <fullName>Events__c</fullName>
    <label>Events</label>
    <referenceTo>Events__c</referenceTo>
    <relationshipLabel>Event-Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Location_Address_Book__c/Location_Address_Book__c.object-meta.xml
<CustomObject>
    <label>Location (Address Book)</label>
    <nameField>
        <label>Location (Address Book) Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/AttendeeController.cls
public class AttendeeController {

    public Attendees__c attendee{get;set;}
    public Event_Attendee__c eventAttendee{get;set;}
    public Location_Address_Book__c location{get;set;}

    public AttendeeController() {
        attendee = new Attendees__c();
        eventAttendee = new Event_Attendee__c();
        location = new Location_Address_Book__c();

        Id currentRecordId  = ApexPages.CurrentPage().getparameters().get('id');
        if(currentRecordId != null) {
            eventAttendee.Events__c = currentRecordId;
        }
    }

    public void Save() {
        Savepoint sp = Database.setSavepoint();
        try {
            insert location;
            attendee.Address__c = location.Id;
            insert attendee;
            eventAttendee.Attendees__c = attendee.Id;
            insert eventAttendee;
        }
        catch(Exception e) {
            Database.rollback(sp);
            ErrorLogRecordInsert.insertErrorLog(e.getMessage(), 'Error Message');
        }
        finally {
            attendee = new Attendees__c();
            eventAttendee = new Event_Attendee__c();
            location = new Location_Address_Book__c();
        }
    }
}