force-app/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>El-{0000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Error_Log__c/fields/Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Process_Name__c</fullName>
    <label>Process Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ErrorLogRecordInsertTest.cls
@isTest private class ErrorLogRecordInsertTest {
    
    @isTest
    static void insertErrorLogTest() {

        String logDetails = 'Testing logDetails';
        String processName = 'Testing processName';

        Test.startTest();
        ErrorLogRecordInsert.insertErrorLog(logDetails,processName);
        Test.stopTest();

        List<Error_Log__c> log  = [Select Id,Log__c,Log_Details__c,Process_Name__c from Error_Log__c];

        System.assertEquals(logDetails,log[0].Log_Details__c);
        System.assertEquals(processName,log[0].Process_Name__c);

    }
    
}