force-app/main/default/objects/Event_Organizer__c/Event_Organizer__c.object-meta.xml
<CustomObject>
    <label>Event Organizer</label>
    <nameField>
        <label>Event Organizer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Events__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location_Address_Book__c</referenceTo>
    <relationshipLabel>Eventss</relationshipLabel>
    <relationshipName>Eventss</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Organizer__c.field-meta.xml
<CustomField>
    <fullName>Organizer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organizer</label>
    <referenceTo>Event_Organizer__c</referenceTo>
    <relationshipLabel>Eventss</relationshipLabel>
    <relationshipName>Eventss</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location_Address_Book__c/Location_Address_Book__c.object-meta.xml
<CustomObject>
    <label>Location (Address Book)</label>
    <nameField>
        <label>Location (Address Book) Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/EventOrganizerController.cls
public class EventOrganizerController {
    public Event_Organizer__c eventOrganizer { get; set; }
    public Location_Address_Book__c eventLocation { get; set; }
    public Events__c event  { get; set; }


    public EventOrganizerController() {
        eventOrganizer = new Event_Organizer__c();
        eventLocation = new Location_Address_Book__c();
        event = new Events__c();
    }


    public void Save() {
        Savepoint sp = Database.setSavepoint();
        try {
            insert eventLocation;
            insert eventOrganizer;

            event.Organizer__c = eventOrganizer.Id;
            if(event.Event_Type__c != 'Virtual') {
                event.Location__c = eventLocation.Id;
            }
            
            insert event;
        }
        catch(Exception e) {
            Database.rollback(sp);
            ErrorLogRecordInsert.insertErrorLog(e.getMessage(), 'Error Message');            
        }

    }

}