force-app/main/default/objects/Event_Speaker__c/Event_Speaker__c.object-meta.xml
<CustomObject>
    <label>Event-Speaker</label>
    <nameField>
        <label>Event- Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event-Speakers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Speaker__c/fields/Events__c.field-meta.xml
<CustomField>
    <fullName>Events__c</fullName>
    <label>Events</label>
    <referenceTo>Events__c</referenceTo>
    <relationshipLabel>Event-Speakers</relationshipLabel>
    <relationshipName>Event_Speakers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/SpeakerController.cls
public class SpeakerController {

    public Speaker__c speaker{get;set;}
    public Event_Speaker__c eventSpeaker{get;set;}

    public SpeakerController() {
        speaker = new Speaker__c();
        eventSpeaker = new Event_Speaker__c();

        Id currentRecordId  = ApexPages.CurrentPage().getparameters().get('id');
        if(currentRecordId != null) {
            eventSpeaker.Events__c = currentRecordId;
        }

    }

    public void Save() {
        Savepoint sp = Database.setSavepoint();
        try {
            insert speaker;
            eventSpeaker.Speaker__c = speaker.Id;
            insert eventSpeaker;
        }
        catch(Exception e) {
            Database.rollback(sp);
            ErrorLogRecordInsert.insertErrorLog(e.getMessage(), 'Error Message');
        }
    }
}