force-app/main/default/objects/Event_Attendee__c/fields/Events__c.field-meta.xml
<CustomField>
    <fullName>Events__c</fullName>
    <label>Events</label>
    <referenceTo>Events__c</referenceTo>
    <relationshipLabel>Event-Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Organizer__c/Event_Organizer__c.object-meta.xml
<CustomObject>
    <label>Event Organizer</label>
    <nameField>
        <label>Event Organizer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Events__c/fields/Live__c.field-meta.xml
<CustomField>
    <fullName>Live__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Live ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location_Address_Book__c</referenceTo>
    <relationshipLabel>Eventss</relationshipLabel>
    <relationshipName>Eventss</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Organizer__c.field-meta.xml
<CustomField>
    <fullName>Organizer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organizer</label>
    <referenceTo>Event_Organizer__c</referenceTo>
    <relationshipLabel>Eventss</relationshipLabel>
    <relationshipName>Eventss</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Recurring__c.field-meta.xml
<CustomField>
    <fullName>Recurring__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Recurring ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Location_Address_Book__c/Location_Address_Book__c.object-meta.xml
<CustomObject>
    <label>Location (Address Book)</label>
    <nameField>
        <label>Location (Address Book) Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/EventAttendeeTriggerTest.cls
@isTest
private class EventAttendeeTriggerTest {
    @isTest
    static void AttendeeEmailHandlerTest() {

        Event_Organizer__c newEventOrg = new Event_Organizer__c();
        newEventOrg.Name = 'Deepanshu';
        insert newEventOrg;

        Location_Address_Book__c newLocation = new 	Location_Address_Book__c();
        newLocation.Name = 'Lucknow';
        insert newLocation;

        Events__c newEvent = new Events__c();
        newEvent.Name__c = 'Singing';
        newEvent.Organizer__c = newEventOrg.Id;
        newEvent.Location__c = newLocation.Id;
        newEvent.Start__c = Datetime.now();
        newEvent.End__c = Datetime.now().addDays(3);
        newEvent.Live__c = true;
        newEvent.Event_Type__c = 'In-Person';
        newEvent.Frequency__c = 'Weekly';
        newEvent.Max_Seats__c = 100;
        newEvent.Recurring__c = true;
        insert newEvent;

        Attendees__c newAttendee = new Attendees__c();
        newAttendee.Name = 'Harshit Kumar';
        newAttendee.Email__c = 'harshit.kumar@mirketa.com';
        newAttendee.Phone__c = '7054089231';
        insert newAttendee;

        Event_Attendee__c newEventAttendee = new Event_Attendee__c();
        newEventAttendee.Attendees__c = newAttendee.Id;
        newEventAttendee.Events__c = newEvent.Id;
        insert newEventAttendee;

        List<Event_Attendee__c> eventAttendeeList = [Select Id ,Attendees__c,Events__c from Event_Attendee__c where Id =: newEventAttendee.Id];

        Test.StartTest();
        AttendeeEmailHandler.sendConfirmationMail(eventAttendeeList);
        Test.StopTest();

        Integer invoice=Limits.getEmailInvocations();
        System.assertEquals(1, invoice,'Email sent');

    }
}