force-app/main/default/objects/Event_Attendee__c/fields/Events__c.field-meta.xml
<CustomField>
    <fullName>Events__c</fullName>
    <label>Events</label>
    <referenceTo>Events__c</referenceTo>
    <relationshipLabel>Event-Attendees</relationshipLabel>
    <relationshipName>Event_Attendees</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Event_Organizer__c/Event_Organizer__c.object-meta.xml
<CustomObject>
    <label>Event Organizer</label>
    <nameField>
        <label>Event Organizer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Organizers</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Events__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location_Address_Book__c</referenceTo>
    <relationshipLabel>Eventss</relationshipLabel>
    <relationshipName>Eventss</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Events__c/fields/Organizer__c.field-meta.xml
<CustomField>
    <fullName>Organizer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organizer</label>
    <referenceTo>Event_Organizer__c</referenceTo>
    <relationshipLabel>Eventss</relationshipLabel>
    <relationshipName>Eventss</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location_Address_Book__c/Location_Address_Book__c.object-meta.xml
<CustomObject>
    <label>Location (Address Book)</label>
    <nameField>
        <label>Location (Address Book) Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/EventAttendeeTriggerHelper.cls
public class EventAttendeeTriggerHelper {

    public static void sendConfirmationMail(List<Event_Attendee__c> attendees){

        Set<Id> attendeeIdSet = new Set<Id>();
        Set<Id> eventIdSet = new Set<Id>();

        for(Event_Attendee__c ea : attendees){
            AttendeeIdSet.add(ea.Attendees__c);
            EventIdSet.add(ea.Events__c);
        }

        Map<Id, Attendees__c> attendeeMap = new Map<Id, Attendees__c>([SELECT Id, Name, Email__c From Attendees__c WHERE  Id IN : attendeeIdSet]);
        Map<Id, Events__c> eventMap = new Map<Id, Events__c>([SELECT Id, Name__c, Start__c, Location__r.Name, Organizer__r.Name From Events__c WHERE  Id IN : eventIdSet]);

        List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();

        for(Event_Attendee__c attendee : attendees){

            Attendees__c Att = attendeeMap.get(attendee.Attendees__c);
            Events__c Eve = eventMap.get(attendee.Events__c);

            String subject = 'Pass For The '+Eve.Name__c;
            String body = 'Dear '+Att.Name+',\n\n';

            body+='Thank you for registering for '+Eve.Name__c+' which will be Organized on '+Eve.Start__c+' at '+Eve.Location__r.Name+' We are excited to have you, see you at the event.\n\n';
            

            body += 'Thanks,\n' +Eve.Organizer__r.Name;

            Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
            email.setToAddresses(new String[]{Att.Email__c});
            email.setSubject(subject);
            email.setPlainTextBody(body);
            emails.add(email);
        }

        List<Messaging.SendEmailResult> results = Messaging.sendEmail(emails, false);
        for(Messaging.SendEmailResult email : results){
            System.debug(email.isSuccess());
        }
    }

}